# your domain
domain: wangxinxing.ml

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use web file
  - https://raw.githubusercontent.com/oouxx/fqsub/master/source.yaml
